USER_NAME = "<Your User Name>"  # TODO
PASSWORD = "<Your Password>"    # TODO
ATCODER_BASE_URL = "https://atcoder.jp"
CONTEST_TYPE_LIST = ["ABC","ARC","AGC"]
CONTEST_PROB_LIST = ["A","B","C","D","E","F","G"]
TEMPLATE_TYPE_LIST = ["generate.py"]
BASE_ROOT_PATH = "<Your Base User's Path>"  # TODO
PYTHON_SHELL_FILEPATH = "<BASE ROOT PATH>/gui/python_test.sh" # TODO
LANGUAGE_LIST = ["cpp","py"]
LANGUAGE_NUM_LIST = [5028,5055]
NORM_LANGUAGE = 0